version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
  angular-service: # The name of the service
    container_name: angularcontainer  # Container name
    build: ./node_angular # Location of our Dockerfile
    volumes: # Volume binding
      - ${APP_CODE_PATH_HOST}:/usr/src/app'
    ports: 
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve"